#! /usr/bin/env bash

#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
#   str="lll.mmm.nnn"
#
#   echo "the shortest name         ${str%%.*}"
#   echo "the longest  name         ${str%.*}"
#
#   echo "the shortest extension    ${str##*.}"
#   echo "the longest  extension    ${str#*.}"
#
#   exit
#

#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
root=$(dirname  $(pwd) )
here=$(basename $(pwd) )

here=$(pwd)

defs=""
args=""

#   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
while [[ $# -gt 0 ]] ; do

    flag=$(printf "%s" $1 | tr [:upper:] [:lower:])

    #flag="${flag%=*}"
    #flag="${flag%:*}"
    #case "${flag:0:2}" in

    case "${flag}" in

        -p | -prefix | --prefix )
            prefix="${2}"
            shift 2
            continue
            ;;

        "-p="* | "-prefix="* | "--prefix="* )
            prefix="${1#*=}"
            shift
            continue
            ;;

        -s | -source | --source )
            source="${2}"
            shift 2
            continue
            ;;

        "-s="* | "-source="* | "--source="* )
            source="${1#*=}"
            shift
            continue
            ;;

    esac

    case "${flag:0:2}" in
        -z )
            defs="$defs -U${1:2}"
            shift
            continue
            ;;

        -u )
            defs="$defs -D${1:2}:BOOL=FALSE"
            shift
            continue
            ;;

        -d )
            if [ "${1%=*}". == "${1#*=}". ] ; then
                defs="$defs -D${1:2}:BOOL=TRUE"
            else
                z="${1:2}"
                defs="$defs -D${z%=*}:STRING=${z#*=}"
            fi
            shift
            continue
            ;;
    esac

    args="$args $1"

    shift

done

# echo "here $here"
# echo "prefix ${here%%.*}"
# echo "source ${here%.*}"

for i in 1 ; do
    if  [ "${source}". == "".  ] ; then
        if  test -f "${here%.*}/CMakeLists.txt" ; then
            source="${here%.*}"
            break
        fi
        SUFS=".src .git .svn"
        for suf in ${SUFS} ; do
            if  test -f "${here%.*}${suf}/CMakeLists.txt" ; then
                source="${here%.*}${suf}"
                break
            fi
        done
    fi
done
if  [ "${source}". == "".  ] ; then
    echo "unable to determine the source directory from ${here} "
    exit
fi
if  ! test -d "${source}" ; then
    echo "source directory not found '${source}' "
    exit
fi

if  [ "${prefix}". == "".  ] ; then
    prefix=${source%.*}
fi

CMAKE="cmake"
CMAKE="${CMAKE} -DCMAKE_EXPORT_COMPILE_COMMANDS=1"
CMAKE="${CMAKE} -DCMAKE_BUILD_TYPE=Release"

if  [ "${prefix}". != "".  ] ; then
    CMAKE="${CMAKE} -DCMAKE_INSTALL_PREFIX=${prefix}"
fi

export CC=/opt/local/bin/gcc-10
export CXX=/opt/local/bin/g++-10
$CMAKE ${defs} ${args} $source
RC=$?

if [ ${RC} -ne 0 ] ; then
    echo "cmake - failed $RC"
fi

exit

